# Simple example of CI to build a Docker container and push it to Amazon ECR
variables:
  DOCKER_REGISTRY: URL_DO_SEU_REPOSITORIO
  NAME_REPO: NOME_DO_SEU_REPOSITORIO
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

publish:
  stage: build
  image: 
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t $NAME_REPO ./app
    - docker tag $NAME_REPO:latest $DOCKER_REGISTRY/$NAME_REPO:latest
    - docker push $DOCKER_REGISTRY/$NAME_REPO:latest
